<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-50659SL" ignored="0" name="Test A" tests="2" failures="2" timestamp="09 Feb 2021 07:17:35 GMT" time="6.027" errors="0">
  <testcase name="testA" time="2.066" classname="suitea.TestA">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	do not match">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
do not match
at suitea.TestA.testA(TestA.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testA -->
  <testcase name="testA" time="2.015" classname="suitea.TestA">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	do not match">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
do not match
at suitea.TestA.testA(TestA.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testA -->
</testsuite> <!-- Test A -->
